# Generated by Django 5.1.15 on 2026-03-15 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GA4Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=50, unique=True)),
                ('property_name', models.CharField(blank=True, max_length=255)),
                ('measurement_id', models.CharField(blank=True, max_length=50)),
                ('gtm_container_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_properties', to='clients.client')),
            ],
            options={
                'verbose_name_plural': 'GA4 properties',
            },
        ),
        migrations.CreateModel(
            name='GA4LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('page_path', models.CharField(db_index=True, max_length=2048)),
                ('organic_sessions', models.IntegerField(default=0)),
                ('organic_users', models.IntegerField(default=0)),
                ('organic_pageviews', models.IntegerField(default=0)),
                ('organic_bounce_rate', models.FloatField(blank=True, null=True)),
                ('organic_avg_session_duration', models.FloatField(blank=True, null=True)),
                ('organic_engagement_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_landing_pages', to='clients.client')),
                ('ga4_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='analytics.ga4property')),
            ],
            options={
                'ordering': ['-date', '-organic_sessions'],
                'indexes': [models.Index(fields=['client', '-date'], name='analytics_g_client__d3374b_idx'), models.Index(fields=['client', 'page_path', '-date'], name='analytics_g_client__8acb81_idx')],
                'unique_together': {('client', 'ga4_property', 'date', 'page_path')},
            },
        ),
        migrations.CreateModel(
            name='GA4Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('event_name', models.CharField(db_index=True, max_length=255)),
                ('is_conversion', models.BooleanField(default=False)),
                ('is_key_event', models.BooleanField(default=False)),
                ('event_count', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('event_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('organic_event_count', models.IntegerField(default=0)),
                ('organic_unique_users', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_events', to='clients.client')),
                ('ga4_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.ga4property')),
            ],
            options={
                'ordering': ['-date', '-event_count'],
                'indexes': [models.Index(fields=['client', '-date'], name='analytics_g_client__448492_idx'), models.Index(fields=['client', 'event_name', '-date'], name='analytics_g_client__68ce3e_idx'), models.Index(fields=['client', 'is_conversion', '-date'], name='analytics_g_client__7068c6_idx')],
                'unique_together': {('client', 'ga4_property', 'date', 'event_name')},
            },
        ),
        migrations.CreateModel(
            name='GA4ConversionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_conversions', models.IntegerField(default=0)),
                ('organic_conversions', models.IntegerField(default=0)),
                ('total_conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('organic_conversion_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('form_submissions', models.IntegerField(default=0)),
                ('phone_clicks', models.IntegerField(default=0)),
                ('chat_starts', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('organic_conversion_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_conversion_summaries', to='clients.client')),
                ('ga4_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_summaries', to='analytics.ga4property')),
            ],
            options={
                'verbose_name_plural': 'GA4 conversion summaries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['client', '-date'], name='analytics_g_client__dc3f23_idx')],
                'unique_together': {('client', 'ga4_property', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GA4TrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('organic_sessions', models.IntegerField(default=0)),
                ('organic_users', models.IntegerField(default=0)),
                ('organic_new_users', models.IntegerField(default=0)),
                ('organic_pageviews', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_pageviews', models.IntegerField(default=0)),
                ('organic_avg_session_duration', models.FloatField(blank=True, null=True)),
                ('organic_bounce_rate', models.FloatField(blank=True, null=True)),
                ('organic_engaged_sessions', models.IntegerField(default=0)),
                ('organic_engagement_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga4_traffic', to='clients.client')),
                ('ga4_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_snapshots', to='analytics.ga4property')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['client', '-date'], name='analytics_g_client__5b2478_idx'), models.Index(fields=['client', 'ga4_property', '-date'], name='analytics_g_client__6eb851_idx')],
                'unique_together': {('client', 'ga4_property', 'date')},
            },
        ),
    ]
