# Generated by Django 5.1.15 on 2026-03-16 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=2048)),
                ('max_pages', models.IntegerField(default=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('pages_crawled', models.IntegerField(default=0)),
                ('pages_with_errors', models.IntegerField(default=0)),
                ('pages_with_warnings', models.IntegerField(default=0)),
                ('total_4xx_errors', models.IntegerField(default=0)),
                ('total_5xx_errors', models.IntegerField(default=0)),
                ('broken_links_count', models.IntegerField(default=0)),
                ('redirect_chains_count', models.IntegerField(default=0)),
                ('duplicate_titles', models.IntegerField(default=0)),
                ('duplicate_descriptions', models.IntegerField(default=0)),
                ('missing_titles', models.IntegerField(default=0)),
                ('missing_descriptions', models.IntegerField(default=0)),
                ('missing_h1', models.IntegerField(default=0)),
                ('missing_alt_tags', models.IntegerField(default=0)),
                ('non_indexable_pages', models.IntegerField(default=0)),
                ('avg_page_load_time', models.FloatField(blank=True, null=True)),
                ('avg_page_size', models.IntegerField(blank=True, null=True)),
                ('has_ssl', models.BooleanField(null=True)),
                ('ssl_pages', models.IntegerField(default=0)),
                ('non_ssl_pages', models.IntegerField(default=0)),
                ('avg_word_count', models.IntegerField(blank=True, null=True)),
                ('thin_content_pages', models.IntegerField(default=0)),
                ('has_robots_txt', models.BooleanField(null=True)),
                ('robots_txt_url', models.URLField(blank=True, max_length=2048)),
                ('has_sitemap', models.BooleanField(null=True)),
                ('sitemap_url', models.URLField(blank=True, max_length=2048)),
                ('is_responsive', models.BooleanField(null=True)),
                ('is_mobile_friendly', models.BooleanField(null=True)),
                ('dataforseo_task_id', models.CharField(blank=True, max_length=255)),
                ('dataforseo_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_audits', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LighthouseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('is_mobile', models.BooleanField(default=True)),
                ('performance_score', models.IntegerField(blank=True, null=True)),
                ('accessibility_score', models.IntegerField(blank=True, null=True)),
                ('best_practices_score', models.IntegerField(blank=True, null=True)),
                ('seo_score', models.IntegerField(blank=True, null=True)),
                ('first_contentful_paint', models.FloatField(blank=True, null=True)),
                ('largest_contentful_paint', models.FloatField(blank=True, null=True)),
                ('total_blocking_time', models.FloatField(blank=True, null=True)),
                ('cumulative_layout_shift', models.FloatField(blank=True, null=True)),
                ('speed_index', models.FloatField(blank=True, null=True)),
                ('time_to_interactive', models.FloatField(blank=True, null=True)),
                ('audits_json', models.JSONField(blank=True, null=True)),
                ('dataforseo_task_id', models.CharField(blank=True, max_length=255)),
                ('dataforseo_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lighthouse_results', to='clients.client')),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lighthouse_results', to='onpage.siteaudit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2048)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('h1', models.CharField(blank=True, max_length=1000)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('content_size', models.IntegerField(blank=True, null=True)),
                ('page_load_time', models.FloatField(blank=True, null=True)),
                ('page_size', models.IntegerField(blank=True, null=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('internal_links_count', models.IntegerField(default=0)),
                ('external_links_count', models.IntegerField(default=0)),
                ('broken_links_count', models.IntegerField(default=0)),
                ('images_count', models.IntegerField(default=0)),
                ('images_missing_alt', models.IntegerField(default=0)),
                ('has_schema', models.BooleanField(default=False)),
                ('schema_types', models.JSONField(blank=True, default=list)),
                ('is_indexable', models.BooleanField(default=True)),
                ('has_canonical', models.BooleanField(default=False)),
                ('canonical_url', models.URLField(blank=True, max_length=2048)),
                ('is_duplicate_title', models.BooleanField(default=False)),
                ('is_duplicate_description', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_pages', to='clients.client')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='onpage.siteaudit')),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.AddIndex(
            model_name='siteaudit',
            index=models.Index(fields=['client', '-created_at'], name='onpage_site_client__b06816_idx'),
        ),
        migrations.AddIndex(
            model_name='lighthouseresult',
            index=models.Index(fields=['client', '-created_at'], name='onpage_ligh_client__1cabe4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditpage',
            index=models.Index(fields=['audit', 'status_code'], name='onpage_audi_audit_i_475f51_idx'),
        ),
        migrations.AddIndex(
            model_name='auditpage',
            index=models.Index(fields=['client', 'url'], name='onpage_audi_client__038de4_idx'),
        ),
    ]
