# Generated by Django 5.1.15 on 2026-03-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='estimated_traffic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='estimated_traffic_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
