# Generated by Django 5.1.15 on 2026-03-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_keyword_estimated_traffic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='current_mobile_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='current_mobile_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='keyword',
            name='mobile_rank_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='previous_mobile_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
