# Generated by Django 5.1.15 on 2026-03-15 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('keywords', '0001_initial'),
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsrankresult',
            name='screenshot_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='mapsrankresult',
            name='serp_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='serpresult',
            name='screenshot_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='serpresult',
            name='serp_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.CreateModel(
            name='LocalFinderResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateField(db_index=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('is_found', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('place_id', models.CharField(blank=True, max_length=255)),
                ('cid', models.CharField(blank=True, max_length=255)),
                ('rating_value', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('rank_change', models.IntegerField(blank=True, null=True)),
                ('previous_rank', models.IntegerField(blank=True, null=True)),
                ('serp_url', models.URLField(blank=True, max_length=2048)),
                ('screenshot_url', models.URLField(blank=True, max_length=2048)),
                ('dataforseo_task_id', models.CharField(blank=True, max_length=255)),
                ('dataforseo_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_finder_results', to='clients.client')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_finder_results', to='keywords.keyword')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['keyword', '-checked_at'], name='rankings_lo_keyword_326ad7_idx'), models.Index(fields=['client', '-checked_at'], name='rankings_lo_client__a39391_idx')],
                'unique_together': {('keyword', 'checked_at')},
            },
        ),
    ]
