# Generated by Django 5.1.15 on 2026-03-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_keyword_current_mobile_rank_and_more'),
        ('rankings', '0002_mapsrankresult_screenshot_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serpresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='serpresult',
            name='device',
            field=models.CharField(default='desktop', max_length=10),
        ),
        migrations.AddField(
            model_name='serpresult',
            name='screenshot_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name='serpresult',
            unique_together={('keyword', 'checked_at', 'device')},
        ),
    ]
