# Generated by Django 5.1.15 on 2026-03-15 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GBPCallMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_calls', models.IntegerField(default=0)),
                ('answered_calls', models.IntegerField(default=0)),
                ('missed_calls', models.IntegerField(default=0)),
                ('avg_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('calls_by_hour', models.JSONField(blank=True, null=True)),
                ('calls_by_day_of_week', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gbp_calls', to='clients.client')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['client', '-date'], name='gmb_gbpcall_client__b42f41_idx')],
                'unique_together': {('client', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GBPPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('business_impressions_desktop_maps', models.IntegerField(default=0)),
                ('business_impressions_desktop_search', models.IntegerField(default=0)),
                ('business_impressions_mobile_maps', models.IntegerField(default=0)),
                ('business_impressions_mobile_search', models.IntegerField(default=0)),
                ('total_impressions', models.IntegerField(default=0)),
                ('call_clicks', models.IntegerField(default=0)),
                ('website_clicks', models.IntegerField(default=0)),
                ('direction_requests', models.IntegerField(default=0)),
                ('business_conversations', models.IntegerField(default=0)),
                ('business_bookings', models.IntegerField(default=0)),
                ('total_interactions', models.IntegerField(default=0)),
                ('photos_views_merchant', models.IntegerField(default=0)),
                ('photos_views_customers', models.IntegerField(default=0)),
                ('photos_count_merchant', models.IntegerField(default=0)),
                ('photos_count_customers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gbp_performance', to='clients.client')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['client', '-date'], name='gmb_gbpperf_client__4c24d4_idx')],
                'unique_together': {('client', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GBPReviewSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('new_reviews_since_last', models.IntegerField(default=0)),
                ('rating_change', models.FloatField(blank=True, null=True)),
                ('five_star', models.IntegerField(default=0)),
                ('four_star', models.IntegerField(default=0)),
                ('three_star', models.IntegerField(default=0)),
                ('two_star', models.IntegerField(default=0)),
                ('one_star', models.IntegerField(default=0)),
                ('total_responded', models.IntegerField(default=0)),
                ('response_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gbp_reviews', to='clients.client')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['client', '-date'], name='gmb_gbprevi_client__d98835_idx')],
                'unique_together': {('client', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GBPSearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('keyword', models.CharField(db_index=True, max_length=500)),
                ('impressions', models.IntegerField(default=0)),
                ('previous_impressions', models.IntegerField(blank=True, null=True)),
                ('impressions_change', models.IntegerField(blank=True, null=True)),
                ('impressions_change_pct', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gbp_search_keywords', to='clients.client')),
            ],
            options={
                'ordering': ['-impressions'],
                'indexes': [models.Index(fields=['client', '-period_start'], name='gmb_gbpsear_client__4ea11d_idx'), models.Index(fields=['client', '-impressions'], name='gmb_gbpsear_client__5fbe38_idx')],
                'unique_together': {('client', 'period_start', 'keyword')},
            },
        ),
    ]
