# Generated by Django 5.1.15 on 2026-03-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('keywords', '0002_keyword_estimated_traffic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('on_page', 'On-Page SEO'), ('gmb', 'Google Business Profile'), ('citations', 'Citations'), ('content', 'Content'), ('link_building', 'Link Building')], default='on_page', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('quarter_start', models.DateField()),
                ('quarter_end', models.DateField()),
                ('month_0_label', models.CharField(blank=True, max_length=20)),
                ('month_1_label', models.CharField(blank=True, max_length=20)),
                ('month_2_label', models.CharField(blank=True, max_length=20)),
                ('month_3_label', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='clients.client')),
            ],
            options={
                'ordering': ['-quarter_start'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=500)),
                ('target_url', models.URLField(blank=True, max_length=2048)),
                ('target_rank', models.IntegerField(blank=True, null=True)),
                ('month_0_rank', models.IntegerField(blank=True, null=True)),
                ('month_1_rank', models.IntegerField(blank=True, null=True)),
                ('month_2_rank', models.IntegerField(blank=True, null=True)),
                ('month_3_rank', models.IntegerField(blank=True, null=True)),
                ('month_0_traffic', models.FloatField(blank=True, null=True)),
                ('month_1_traffic', models.FloatField(blank=True, null=True)),
                ('month_2_traffic', models.FloatField(blank=True, null=True)),
                ('month_3_traffic', models.FloatField(blank=True, null=True)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('keyword_difficulty', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='keywords.keyword')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.quarterlyplan')),
            ],
            options={
                'ordering': ['-priority', 'keyword_text'],
            },
        ),
        migrations.AddIndex(
            model_name='quarterlyplan',
            index=models.Index(fields=['client', '-quarter_start'], name='plans_quart_client__86c8af_idx'),
        ),
        migrations.AddIndex(
            model_name='planitem',
            index=models.Index(fields=['plan', '-priority'], name='plans_plani_plan_id_f3c28d_idx'),
        ),
    ]
