# Generated by Django 5.1.15 on 2026-03-16 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_keyword_estimated_traffic_and_more'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planitem',
            options={'ordering': ['category', '-priority', 'keyword_text']},
        ),
        migrations.RemoveField(
            model_name='quarterlyplan',
            name='category',
        ),
        migrations.AddField(
            model_name='planitem',
            name='category',
            field=models.CharField(choices=[('on_page', 'On-Page SEO'), ('gmb', 'Google Business Profile'), ('citations', 'Citations'), ('content', 'Content'), ('link_building', 'Link Building'), ('technical', 'Technical SEO')], default='on_page', max_length=20),
        ),
        migrations.AddField(
            model_name='planitem',
            name='citation_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='planitem',
            name='citation_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='planitem',
            name='content_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='planitem',
            name='content_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='planitem',
            name='link_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='planitem',
            name='link_target_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='planitem',
            name='publish_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='planitem',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='keywords.keyword'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='keyword_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='planitem',
            index=models.Index(fields=['plan', 'category'], name='plans_plani_plan_id_9e04ff_idx'),
        ),
    ]
