# Generated by Django 5.1.15 on 2026-03-16 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_planitem_options_remove_quarterlyplan_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('gmb_post_type', models.CharField(blank=True, max_length=50)),
                ('gmb_post_cta', models.CharField(blank=True, max_length=100)),
                ('gmb_post_image_url', models.URLField(blank=True, max_length=2048)),
                ('on_page_action', models.CharField(blank=True, max_length=100)),
                ('assignee', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='plans.planitem')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
                'indexes': [models.Index(fields=['plan_item', 'status'], name='plans_deliv_plan_it_145a88_idx'), models.Index(fields=['plan_item', 'due_date'], name='plans_deliv_plan_it_1eab95_idx')],
            },
        ),
    ]
