# Generated by Django 5.1.15 on 2026-03-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryresult',
            name='competitor_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='discoveryresult',
            name='source',
            field=models.CharField(choices=[('ranked', 'Already Ranking'), ('competitor_gap', 'Competitor Gap')], default='ranked', max_length=20),
        ),
    ]
