# Generated by Django 5.1.15 on 2026-03-16 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMentionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('date', models.DateField(db_index=True)),
                ('total_mentions', models.IntegerField(default=0)),
                ('positive_mentions', models.IntegerField(default=0)),
                ('negative_mentions', models.IntegerField(default=0)),
                ('neutral_mentions', models.IntegerField(default=0)),
                ('avg_sentiment_score', models.FloatField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_mention_snapshots', to='clients.client')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContentMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('snippet', models.TextField(blank=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=10)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('social_shares', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_mentions', to='clients.client')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='content_analysis.contentmentionsnapshot')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.AddIndex(
            model_name='contentmentionsnapshot',
            index=models.Index(fields=['client', '-date'], name='content_ana_client__e0d73f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentmentionsnapshot',
            unique_together={('client', 'keyword', 'date')},
        ),
        migrations.AddIndex(
            model_name='contentmention',
            index=models.Index(fields=['client', '-publication_date'], name='content_ana_client__ed8e07_idx'),
        ),
        migrations.AddIndex(
            model_name='contentmention',
            index=models.Index(fields=['client', 'sentiment'], name='content_ana_client__0413e0_idx'),
        ),
    ]
