# Generated by Django 5.1.15 on 2026-03-16 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklinkSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_backlinks', models.IntegerField(default=0)),
                ('referring_domains', models.IntegerField(default=0)),
                ('referring_ips', models.IntegerField(default=0)),
                ('broken_backlinks', models.IntegerField(default=0)),
                ('broken_pages', models.IntegerField(default=0)),
                ('dofollow', models.IntegerField(default=0)),
                ('nofollow', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('backlinks_change', models.IntegerField(blank=True, null=True)),
                ('domains_change', models.IntegerField(blank=True, null=True)),
                ('new_backlinks', models.IntegerField(default=0)),
                ('lost_backlinks', models.IntegerField(default=0)),
                ('new_referring_domains', models.IntegerField(default=0)),
                ('lost_referring_domains', models.IntegerField(default=0)),
                ('dataforseo_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlink_snapshots', to='clients.client')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Backlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2048)),
                ('source_domain', models.CharField(db_index=True, max_length=255)),
                ('source_title', models.CharField(blank=True, max_length=1000)),
                ('target_url', models.URLField(max_length=2048)),
                ('anchor', models.CharField(blank=True, max_length=1000)),
                ('link_type', models.CharField(blank=True, max_length=20)),
                ('is_dofollow', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('source_rank', models.IntegerField(blank=True, null=True)),
                ('source_spam_score', models.IntegerField(blank=True, null=True)),
                ('first_seen', models.DateField(blank=True, null=True)),
                ('last_seen', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlinks', to='clients.client')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlinks', to='backlinks.backlinksnapshot')),
            ],
            options={
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='AnchorText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor', models.CharField(db_index=True, max_length=1000)),
                ('backlinks_count', models.IntegerField(default=0)),
                ('referring_domains', models.IntegerField(default=0)),
                ('dofollow', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_texts', to='clients.client')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='backlinks.backlinksnapshot')),
            ],
            options={
                'ordering': ['-backlinks_count'],
            },
        ),
        migrations.CreateModel(
            name='ReferringDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('backlinks_count', models.IntegerField(default=0)),
                ('dofollow_count', models.IntegerField(default=0)),
                ('nofollow_count', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('spam_score', models.IntegerField(blank=True, null=True)),
                ('first_seen', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referring_domains', to='clients.client')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_domains', to='backlinks.backlinksnapshot')),
            ],
            options={
                'ordering': ['-backlinks_count'],
            },
        ),
        migrations.AddIndex(
            model_name='backlinksnapshot',
            index=models.Index(fields=['client', '-date'], name='backlinks_b_client__ae0e5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backlinksnapshot',
            unique_together={('client', 'date')},
        ),
        migrations.AddIndex(
            model_name='backlink',
            index=models.Index(fields=['client', '-first_seen'], name='backlinks_b_client__2f895e_idx'),
        ),
        migrations.AddIndex(
            model_name='backlink',
            index=models.Index(fields=['client', 'source_domain'], name='backlinks_b_client__6e5674_idx'),
        ),
        migrations.AddIndex(
            model_name='referringdomain',
            index=models.Index(fields=['client', '-backlinks_count'], name='backlinks_r_client__aba57a_idx'),
        ),
    ]
