# Generated by Django 5.1.15 on 2026-03-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('website_url', models.URLField(blank=True, max_length=2048)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('google_business_name', models.CharField(blank=True, max_length=255)),
                ('google_place_id', models.CharField(blank=True, max_length=255)),
                ('google_cid', models.CharField(blank=True, max_length=255)),
                ('location_code', models.IntegerField(default=2840)),
                ('location_name', models.CharField(default='United States', max_length=255)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('track_organic', models.BooleanField(default=True)),
                ('track_maps', models.BooleanField(default=False)),
                ('discovery_enabled', models.BooleanField(default=True)),
                ('max_discovery_keywords', models.IntegerField(default=1000)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('monthly_budget_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
