# Generated by Django 5.1.15 on 2026-03-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='track_mobile',
            field=models.BooleanField(default=True),
        ),
    ]
