# Generated by Django 5.1.15 on 2026-03-28 10:36

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    for client in Client.objects.filter(slug=''):
        base = slugify(client.name)
        slug = base
        n = 1
        while Client.objects.filter(slug=slug).exclude(pk=client.pk).exists():
            slug = f"{base}-{n}"
            n += 1
        client.slug = slug
        client.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_track_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
